include:
  - mqtt-broker.yml

services:
  git:
    image: alpine/git
    volumes:
      - .:/app
  react-mtqq:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/app/node_modules
    depends_on:
      - mqtt-broker
      - git

volumes:
  node_modules:
